# BLOQUE 1

In [6]:
import pandas as pd
import numpy as np

#print(pd.__version__)

df = pd.read_csv("healthcheck_colombia.csv")
print(df.shape)
df.head(10)

(350, 13)

,id_trabajador,edad,ciudad,cargo,sector,nivel,anios_experiencia,horas_semana,salario_cop,nivel_estres,dias_ausencia_anio,satisfaccion_laboral,fecha_ingreso
0,1001,28,Bogotá,QA Engineer,Fintech,Junior,1,48.0,10859922.0,2.0,10.0,6.0,01/01/2018
1,1002,41,Barranquilla,UX Designer,Consultoría,Junior,9,56.0,6190583.0,8.0,6.0,8.0,04/01/2018
2,1003,50,Barranquilla,Desarrollador Junior,E-commerce,Lead,11,50.0,4099908.0,6.0,4.0,6.0,07/01/2018
3,1004,36,Bogotá,UX Designer,Healthtech,Senior,16,46.0,4664412.0,4.0,16.0,9.0,10/01/2018
4,1005,32,Medellín,Desarrollador Junior,Healthtech,Mid,7,53.0,7809792.0,5.0,19.0,9.0,13/01/2018
5,1006,29,Bogotá,Data Analyst,Edtech,Mid,10,58.0,4853847.0,8.0,8.0,2.0,16/01/2018
6,1007,50,Barranquilla,QA Engineer,Edtech,Mid,2,43.0,5392478.0,3.0,13.0,10.0,19/01/2018
7,1008,42,Bucaramanga,DevOps,Consultoría,Junior,5,45.0,NaN,NaN,11.0,1.0,22/01/2018
8,1009,28,Bucaramanga,Product Manager,Consultoría,Lead,8,49.0,8449852.0,4.0,5.0,2.0,25/01/2018
9,1010,47,Cali,Desarrollador Junior,Fintech,Mid,5,46.0,2529725.0,1.0,16.0,5.0,28/01/2018

In [8]:
df.dtypes

id_trabajador             int64
edad                      int64
ciudad                      str
cargo                       str
sector                      str
nivel                       str
anios_experiencia         int64
horas_semana            float64
salario_cop             float64
nivel_estres            float64
dias_ausencia_anio      float64
satisfaccion_laboral    float64
fecha_ingreso               str
dtype: object

In [9]:
df.describe()

,id_trabajador,edad,anios_experiencia,horas_semana,salario_cop,nivel_estres,dias_ausencia_anio,satisfaccion_laboral
count,350.000000,350.000000,350.000000,350.000000,3.150000e+02,322.000000,350.000000,328.000000
mean,1175.500000,36.942857,8.705714,49.517143,7.477139e+06,5.260870,9.994286,5.347561
std,101.180532,9.229773,5.700925,6.387083,5.613608e+06,2.848231,11.024847,2.880058
min,1001.000000,22.000000,0.000000,40.000000,2.519675e+06,0.000000,0.000000,1.000000
25%,1088.250000,29.000000,4.000000,44.000000,5.008809e+06,3.000000,5.000000,3.000000
50%,1175.500000,37.000000,9.000000,49.000000,7.198713e+06,5.000000,10.000000,5.000000
75%,1262.750000,45.750000,13.000000,54.750000,9.496370e+06,8.000000,14.000000,8.000000
max,1350.000000,51.000000,54.000000,97.000000,9.500000e+07,10.000000,187.000000,10.000000

In [11]:
# Obtiene la cantidad de nulos de cada columna del dataset
df.isnull().sum()

id_trabajador            0
edad                     0
ciudad                  15
cargo                    0
sector                   0
nivel                    0
anios_experiencia        0
horas_semana             0
salario_cop             35
nivel_estres            28
dias_ausencia_anio       0
satisfaccion_laboral    22
fecha_ingreso            0
dtype: int64

## No todos los nulos son iguales

### TIPO QUÉ SIGNFICA
MCAR:    Falta complementar al azar, cuando el nulo no tiene relación con otras variables, ni con el valor que falta.  
MAR:     Relacionado con otra variable,   
MNAR:    Relacionado con el valor que falta  

¿Con qué valor reemplazamos el hueco?

### ESTRATEGIA  CUÁNDO USARLA  
Media:      Numérica, distribución simétrica, sin outliers.  mean()  
Mediana:    Numérica con outliers o distribución sesgada. median()     
Moda:       Variable categórica. mode()  
Por grupo:  El nulo depende de otra variable

In [23]:
# Imputación 1 Salario ---> Mediana

# Aquí se toma la columna salario_cop del DataFrame df y se calcula su mediana.
mediana_salario = df['salario_cop'].median()
print(f"Mediana de salario: ${mediana_salario:,.0f}")

# fillna() reemplaza todos los valores vacíos o nulos (NaN) de la columna salario_cop por el valor de la mediana.
df['salario_cop'] = df['salario_cop'].fillna(mediana_salario)

Mediana de salario: $7,198,713

In [15]:
# Imputación 2 ---> Nivel Estres, Media
media_estres = df['nivel_estres'].mean()
print(f"Media de Nivel Estres: ${media_estres}")

df['nivel_estres'] = df['nivel_estres'].fillna(media_estres)

Media de Nivel Estres: $5.260869565217392

In [17]:
# Imputación 3, Satisfación laboral
mediana_laboral = df['satisfaccion_laboral'].median()
print(f"Mediana de Satisfación laboral: ${mediana_laboral}")

df['satisfaccion_laboral'] = df['satisfaccion_laboral'].fillna(mediana_laboral)

Mediana de Satisfación laboral: $5.347560975609756

In [24]:
# Imputación 4, ciudad con moda

# Aquí el código toma la columna ciudad del DataFrame df y calcula su moda. [0] se toma el primer valor de esa serie.
ciudad_moda = df['ciudad'].mode()[0]
print(f'Moda de la ciudad: {ciudad_moda}')

# Esta línea reemplaza todos los valores vacíos (NaN) de la columna ciudad por la moda calculada.
df['ciudad'] = df['ciudad'].fillna(ciudad_moda)

Moda de la ciudad: Bucaramanga

In [22]:
# Se valida de nuevo el DataFrame y ya no debe tener datos nulos
df.isnull().sum()

id_trabajador           0
edad                    0
ciudad                  0
cargo                   0
sector                  0
nivel                   0
anios_experiencia       0
horas_semana            0
salario_cop             0
nivel_estres            0
dias_ausencia_anio      0
satisfaccion_laboral    0
fecha_ingreso           0
dtype: int64

## Cuartiles

EL IQR es la distancia entre Q1 y Q3
$$
IQR = Q3 - Q1
$$
$$
Limite\;superior = Q1 - (1.5*IQR)
$$
$$
Limite\;inferior = Q3 + (1.5*IQR)
$$

In [ ]:
Q1 = df['horas_semana'].quantile(0.25)
Q3 = df['horas_semana'].quantile(0.75)
df.

IQR = Q3 - Q1

print(f"Q1: {Q1}")
print(f"Q3: {Q3}")
print(f"IQR: {IQR}")

Q1: 44.0
Q3: 54.75
IQR: 10.75

In [29]:
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print(f"Límite inferior: {limite_inferior:.2f} horas")
print(f"Límite superior: {limite_superior:.2f} horas")

Límite inferior: 27.88 horas
Límite superior: 70.88 horas

In [35]:
# Identificar outliers a través de los límites inferior y superior

outliers_iqr = df[
    (df['horas_semana'] < limite_inferior) |
    (df['horas_semana'] > limite_superior)
]

print(f"Outliers detectados en horas_semana: {len(outliers_iqr)}")
print(outliers_iqr[['id_trabajador', 'cargo', 'nivel', 'horas_semana']])

Outliers detectados en horas_semana: 1
    id_trabajador                 cargo   nivel  horas_semana
12           1013  Desarrollador Junior  Junior          97.0

### Valor Z
$$
Z = \frac{(valor - media)}{desviacion\;estandar}
$$

Grupo A — Salarios: $4.9M, $5.0M, $5.1M, $5.0M, $5.0M
→ Media = $5M, Desviación estándar ≈ $0.07M (muy agrupados)

Grupo B — Salarios: $2M, $3.5M, $5M, $6.5M, $8M
→ Media = $5M, Desviación estándar ≈ $2.2M (muy dispersos)

Z = (95.000.000 - 5.000.000) / (2.000.000) = 45.000.000